version: "3"
   
services:
  backend:
    container_name: backend-digitalcode
    build: ./digitalcode
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './digitalcode:/app/digitalcode'
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  frontend-movie:
    container_name: frontend-digitalcode
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - './frontend:/app/frontend'
      - '/app/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend